package com.bookstore.entity;
// Generated Dec 6, 2020, 5:28:21 PM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "bookstoredb")
@NamedQueries({
	@NamedQuery(name="Category.findAll", query="Select c From Category c ORDER BY c.name"),
	@NamedQuery(name="Category.countAll", query="SELECT Count(c) FROM Category c"),
	@NamedQuery(name="Category.findByName", query="Select c From Category c Where c.name=:name")
})
public class Category implements java.io.Serializable {

	private int categoryId;
	private String name;
	private Serializable books = new HashSet(0);
	public Category() {
		
	
	}


	public Category( String name) {
	this.name=name;
	}


	public Category(int categoryId, String name) {
		this.categoryId = categoryId;
		this.name = name;
	}

	public Category(int categoryId, String name, Set<Book> books) {
		this.categoryId = categoryId;
		this.name = name;
		this.books = (Serializable) books;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@SuppressWarnings("unchecked")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Book> getBooks() {
		return (Set<Book>) this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = (Serializable) books;
	}

}

